name: Electem IOT CI

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Importing DB
        continue-on-error: true
        run: |
          echo "Importing DB"
          export PGPASSWORD=xvRFk60dg5W4&& psql -h 209.133.209.251 -p 5432 -U dypmbjde_rmstest -d dypmbjde_rms_test -f db/db-cypress.sql
          
          yes | cp -rf Back-End/app/config/test-workflow.config.ts Back-End/app/config/db.config.ts
          yes | cp -rf Back-End/app/test.module.ts Back-End/app/app.module.ts
          
      - name: Run Backend
        continue-on-error: true
        run: |
          cd Back-End
          npm install --force
          npm install @nestjs/cli --global
          nohup npm run build > nohup.out 2> nohup.err < /dev/null &
          sleep 20
          nohup npm run start > nohup_run.out 2> nohup_run.err < /dev/null &	  
          sleep 60
          telnet localhost 3000
          
      - name: Run Frontend
        continue-on-error: true
        run: |
          cd Front-End
          npm install --force
          nohup npm start > nohup.out 2> nohup.err < /dev/null &
          sleep 120
          telnet localhost 4200

      - name: Cypress run
        continue-on-error: true
        uses: cypress-io/github-action@v6
        with:
          working-directory: Front-End
          install: false
          wait-on: http://127.0.0.1:4200/
          browser: chrome
          config-file: cypress.config.ts
          spec: cypress/e2e/allspec.cy.ts
          
      - name: Run zip results
        continue-on-error: true
        run: |
          cp -f /home/runner/work/Rack-Management/Rack-Management/Back-End/nohup.out /home/runner/work/Rack-Management/Rack-Management/Front-End/cypress/nohup_backend.out
          cp -f /home/runner/work/Rack-Management/Rack-Management/Back-End/nohup.err /home/runner/work/Rack-Management/Rack-Management/Front-End/cypress/nohup_backend.err
          cp -f /home/runner/work/Rack-Management/Rack-Management/Front-End/nohup.out /home/runner/work/Rack-Management/Rack-Management/Front-End/cypress/nohup_frontend.out
          cp -f /home/runner/work/Rack-Management/Rack-Management/Front-End/nohup.err /home/runner/work/Rack-Management/Rack-Management/Front-End/cypress/nohup_frontend.err
          cd /home/runner/work/Rack-Management/Rack-Management/Front-End
          zip -r result.zip cypress/*
          ls -lrt

      - uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: /home/runner/work/Rack-Management/Rack-Management/Front-End/cypress/screenshots
          
      - name: Release with Notes
        uses: softprops/action-gh-release@v1        
        with:
          tag_name: "Cypress_artifacts"
          files: |
            /home/runner/work/Rack-Management/Rack-Management/Front-End/result.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WF_TOKEN }}
